### ISSUE TITLE
I think the arguments should be switched

### ISSUE THREAD

**Issue by abrelsfo** [jonschlinkert/in-array#1]
I feel like the arguments should be element then array. If you write out the order in english it would be is this element in this array. I find it confusing to put the array first.

**Comment by tunnckoCore** [comment]
~~also, it will follow the `indexOf` which is `array.indexOf(element)` as @abrelsfo saying.~~

**Comment by tunnckoCore** [comment]
Oh, yea yea. Actually it currently follows indexOf!

**Comment by jonschlinkert** [comment]
> Actually it currently follows indexOf!

yeah that's why I did it that way. I do see your point @abrelsfo, but it's equally valid to read it as: "In array `[]`, is there a `???`?

closing since it probably wouldn't be a good idea to switch arguments at this point

**Comment by tunnckoCore** [comment]
I also created http://npm.im/arr-includes adding support for checking if any of multiple values exists in array. :) It also works as `in-array`.

Cheers,
Charlike!
